version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  hc-engine-app:
    build: 
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
